-- MySQL Script generated by MySQL Workbench
-- Tue Nov 24 03:00:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bairro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Bairro` (
  `Id_Bairro` INT NOT NULL,
  `Nome_Bairro` VARCHAR(45) NOT NULL,
  `Id_Cidade` INT NOT NULL,
  PRIMARY KEY (`Id_Bairro`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Bairro_UNIQUE` ON `Bairro` (`Id_Bairro` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cidade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cidade` (
  `Id_Cidade` INT NOT NULL,
  `Nome_Cidade` VARCHAR(45) NOT NULL,
  `Id_UF` INT NOT NULL,
  PRIMARY KEY (`Id_Cidade`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Cidade_UNIQUE` ON `Cidade` (`Id_Cidade` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `Id_Cliente` INT NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `RG` VARCHAR(7) NOT NULL,
  `Status_Cliente` VARCHAR(45) NOT NULL COMMENT 'Médio\nBom\nRuim',
  `Limite_de_Credito` FLOAT NOT NULL,
  `Sexo` VARCHAR(45) NULL,
  `Estado_Civil` VARCHAR(45) NOT NULL,
  `Data_Nascimento` DATE NOT NULL,
  `Naturalidade` VARCHAR(45) NOT NULL,
  `Id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`Id_Cliente`, `CPF`, `RG`, `Id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CPF_UNIQUE` ON `Cliente` (`CPF` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Cliente_UNIQUE` ON `Cliente` (`Id_Cliente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Pessoa_UNIQUE` ON `Cliente` (`Id_Pessoa` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `RG_UNIQUE` ON `Cliente` (`RG` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Endereco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Endereco` (
  `Id_Endereco` INT NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `Numero_Casa` INT NOT NULL,
  `Nome_Rua` VARCHAR(45) NOT NULL,
  `Id_Tipo_Endereco` INT NOT NULL,
  `Id_Bairro` INT NOT NULL,
  PRIMARY KEY (`CEP`, `Id_Endereco`, `Id_Tipo_Endereco`, `Id_Bairro`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Endereco_UNIQUE` ON `Endereco` (`Id_Endereco` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CEP_UNIQUE` ON `Endereco` (`CEP` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Filiacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Filiacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Filiacao` (
  `Id_Filiacao` INT NOT NULL,
  `Nome_Mae` VARCHAR(100) NOT NULL,
  `Nome_Pai` VARCHAR(100) NULL,
  `Id_Cliente` INT NOT NULL,
  PRIMARY KEY (`Id_Filiacao`, `Id_Cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Filiacao_UNIQUE` ON `Filiacao` (`Id_Filiacao` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Cliente_UNIQUE` ON `Filiacao` (`Id_Cliente` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Fornecedor` (
  `Id_Fornecedor` INT NOT NULL,
  `CNPJ` VARCHAR(14) NOT NULL,
  `Nome_Fantasia` VARCHAR(45) NOT NULL,
  `Id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`Id_Fornecedor`, `CNPJ`, `Id_Pessoa`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Fornecedor_UNIQUE` ON `Fornecedor` (`Id_Fornecedor` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CNPJ_UNIQUE` ON `Fornecedor` (`CNPJ` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Nota` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Nota` (
  `Id_Nota` INT NOT NULL,
  `Numero_Nota` VARCHAR(8) NOT NULL,
  `Data_Elaboracao` DATE NOT NULL,
  `Quantidade_Produtos` INT NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Id_Cliente` INT NOT NULL,
  PRIMARY KEY (`Id_Nota`, `Numero_Nota`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Pedido_UNIQUE` ON `Nota` (`Id_Nota` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Numero_Pedido_UNIQUE` ON `Nota` (`Numero_Nota` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pais` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pais` (
  `Id_Pais` INT NOT NULL,
  `Nome_Pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Pais`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Pais_UNIQUE` ON `Pais` (`Id_Pais` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pedido` (
  `Id_Pedido` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Quantidade` INT NOT NULL,
  `Preco` FLOAT NOT NULL,
  `Id_Nota` INT NOT NULL,
  `Codigo_Produto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Pedido`, `Id_Nota`, `Codigo_Produto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pessoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pessoa` (
  `Id_Pessoa` INT NOT NULL,
  `Nome_Pessoa` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Id_Tipo` INT NOT NULL,
  `Id_Endereco` INT NOT NULL,
  PRIMARY KEY (`Id_Pessoa`, `Id_Endereco`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Pessoa_UNIQUE` ON `Pessoa` (`Id_Pessoa` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto` (
  `Id_Produto` INT NOT NULL,
  `Codigo_Produto` VARCHAR(45) NOT NULL,
  `Nome_Produto` VARCHAR(45) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Data_Validade` DATE NOT NULL,
  `Data_Fabricacao` DATE NOT NULL,
  `Preco` FLOAT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Id_Fornecedor` INT NOT NULL,
  PRIMARY KEY (`Id_Produto`, `Codigo_Produto`, `Id_Fornecedor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Produto_UNIQUE` ON `Produto` (`Id_Produto` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Codigo_Produto_UNIQUE` ON `Produto` (`Codigo_Produto` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Telefone` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Telefone` (
  `Id_Telefone` INT NOT NULL,
  `DDD` INT NOT NULL,
  `Numero_Telefone` INT NOT NULL,
  `Id_Pessoa` INT NOT NULL,
  PRIMARY KEY (`Id_Telefone`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tipo_Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tipo_Endereco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tipo_Endereco` (
  `Id_Tipo_Endereco` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Tipo_Endereco`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Tipo_Endereco_UNIQUE` ON `Tipo_Endereco` (`Id_Tipo_Endereco` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tipo_de_Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tipo_de_Pessoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tipo_de_Pessoa` (
  `Id_Tipo` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Tipo`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Tipo_UNIQUE` ON `Tipo_de_Pessoa` (`Id_Tipo` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UF` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UF` (
  `Id_UF` INT NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `Nome_Estado` VARCHAR(45) NOT NULL,
  `Id_Pais` INT NOT NULL,
  PRIMARY KEY (`Id_UF`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_UF_UNIQUE` ON `UF` (`Id_UF` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
